/* ================= 衣橱数据 =================
   每件单品一条记录；新增衣服在 ITEMS 末尾追加即可。
   img 指向 images/ 下的产品图（白底，网站用正片叠底融合）。 */
const ITEMS = [
  {id:'001', img:'images/r001_white-tank.webp', en:'WHITE SQUARE-NECK TANK', cn:'白色方领背心', cat:'TOPS', season:'春夏',
   pal:['#e8e6e0','#a3aaa5','#4f6164'], notes:'简洁方领修身背心 · 配牛仔长裙很飒'},
  {id:'003', img:'images/r003_baroque-halter.webp', en:'BAROQUE HALTER TOP', cn:'黑花纹吊带抹胸', cat:'TOPS', season:'夏',
   pal:['#f5cdac','#9c3325','#3a2a20'], notes:'复古提花细吊带 · 度假感'},
  {id:'004', img:'images/r004_brown-cami.webp', en:'BROWN RUCHED CAMI', cn:'棕色褶皱吊带上衣', cat:'TOPS', season:'夏',
   pal:['#63595a','#a9a298','#28272a'], notes:'胸前抽褶设计 · 慵懒性感'},
  {id:'005', img:'images/r005_white-halter-dress.webp', en:'WHITE HALTER DRESS', cn:'白色黑边挂脖连衣裙', cat:'DRESSES', season:'夏',
   pal:['#e6e2db','#dab295','#1a1a1a'], notes:'极简针织挂脖长裙 · 黑色包边勾勒线条'},
  {id:'007', img:'images/007.webp', en:'WHITE BASIC TEE', cn:'白色基础T恤', cat:'TOPS', season:'四季',
   pal:['#e7e8e9','#d5d7d8','#bfc2c3'], notes:'万能白T · 怎么搭都行 · 纯棉'},
  {id:'008', img:'images/r008_black-hoodie.webp', en:'BLACK OVERSIZED HOODIE', cn:'黑色连帽卫衣', cat:'TOPS', season:'秋冬',
   pal:['#1b1b1e','#d3c5b8','#e4e5e6'], notes:'oversize 黑卫衣 · 配缎面长裙混搭高级'},
  {id:'009', img:'images/r009_navy-zip-jacket.webp', en:'NAVY ZIP JACKET', cn:'藏青拉链短外套', cat:'JACKETS', season:'春秋',
   pal:['#15141c','#615f6a','#8b93a5'], notes:'学院风短外套 · 内搭格纹衬衫有层次'},
  {id:'010', img:'images/010.webp', en:'GREEN STRIPE KNIT VEST', cn:'绿白条纹针织背心', cat:'TOPS', season:'春夏',
   pal:['#2c8a56','#e0d9cf','#a08e76'], notes:'清新条纹小背心 · 元气显白'},
  {id:'011', img:'images/r011_black-banana-pants.webp', en:'BLACK BANANA PANTS', cn:'黑色阔腿香蕉裤', cat:'BOTTOMS', season:'四季',
   pal:['#101418','#595d5f','#e2e4e6'], notes:'弧形轮廓阔腿裤 · 遮肉显瘦 · 垂感面料'},
  {id:'012', img:'images/r012_oat-hoodie.webp', en:'OAT PRINT HOODIE', cn:'燕麦色印花连帽卫衣', cat:'TOPS', season:'秋冬',
   pal:['#d3c8ba','#b5a596','#7a6a55'], notes:'The Secret Garden 印花 · 加绒软乎乎'},
  {id:'013', img:'images/013.webp', en:'STRIPE CABLE-KNIT ZIP CARDIGAN', cn:'蓝灰条纹麻花针织开衫', cat:'JACKETS', season:'秋冬',
   pal:['#9c999d','#ded6ce','#6d7484'], notes:'拉链连帽麻花针织 · 学院感满分 · 羊毛混纺'},
  {id:'014', img:'images/r014_white-work-pants.webp', en:'WHITE STITCH WORK PANTS', cn:'白色明线工装直筒裤', cat:'BOTTOMS', season:'四季',
   pal:['#dee0df','#aeaaa1','#222728'], notes:'MOUSSY · 明线设计 · 直筒利落'},
  {id:'021', img:'images/021.webp', en:'GREEN RINGER TEE', cn:'绿边 Ringer T恤', cat:'TOPS', season:'春夏',
   pal:['#e9e8e4','#169d65','#a0caab'], notes:'MRS Studios · A votre santé 复古滚边'},
  {id:'026', img:'images/r026_denim-skirt.webp', en:'BLACK SLIT DENIM SKIRT', cn:'黑色开衩牛仔长裙', cat:'BOTTOMS', season:'四季',
   pal:['#272729','#5a5a5c','#d5ab95'], notes:'高开衩毛边下摆 · 酷感直筒裙'},
  {id:'027', img:'images/r027_navy-dress.webp', en:'NAVY COLLARED DRESS', cn:'藏青娃娃领连衣裙', cat:'DRESSES', season:'春秋',
   pal:['#181f23','#eae6da','#524f36'], notes:'白色娃娃领 + 泡泡袖 · 法式复古'},
  {id:'f01', img:'images/figma_01_3-172.webp', en:'CAMEL TRENCH COAT', cn:'驼色双排扣风衣', cat:'JACKETS', season:'春秋',
   pal:['#caa98b','#b59174','#8a6a4d'], notes:'经典系带双排扣 · 通勤百搭'},
  {id:'t01', img:'images/taobao_01_2026-03-08_ITSNIKAR.webp', en:'BLACK WIDE-LEG TROUSERS', cn:'黑色低腰阔腿西装裤', cat:'BOTTOMS', season:'四季',
   pal:['#222324','#5f5f60','#a0a1a1'], notes:'ITSNIKAR · 垂感阔腿 · 腿长两米'},
  {id:'t02', img:'images/taobao_02_2026-03-08_ITSNIKAR.webp', en:'GRAY SLIM TEE', cn:'灰色修身短袖T恤', cat:'TOPS', season:'春夏',
   pal:['#c6c7c6','#a8a9a8','#8f918f'], notes:'ITSNIKAR · 基础修身小T · 好叠穿'},
  {id:'t03', img:'images/taobao_03_2026-03-08_NO_LOGO_OFFICAL.webp', en:'CREAM MOCK-NECK SWEATSHIRT', cn:'米白小高领卫衣', cat:'TOPS', season:'秋冬',
   pal:['#eeece1','#ddd9c8','#c9c4b0'], notes:'NO LOGO · 简约小高领 · 干净耐看'},
  {id:'t06', img:'images/rt06_suede-vest.webp', en:'BROWN SUEDE VEST', cn:'棕色麂皮马甲', cat:'JACKETS', season:'春秋',
   pal:['#632910','#91642d','#6e5724'], notes:'陌素小姐 · 手工缝边西部风 · 配泡泡袖衬衫绝了'},
  {id:'s01', img:'images/selfie_01_2026-08-01_wide-pants.webp', en:'CHARTREUSE WIDE-LEG PANTS', cn:'黄绿色系带阔腿裤', cat:'BOTTOMS', season:'春夏',
   pal:['#c9b81f','#8f841c','#2b2b2d'], notes:'AI 重绘自日常照 · 黑色织带腰扣 · 皱面尼龙'},
  {id:'s02', img:'images/s02_beige-tee.webp', en:'BEIGE OVERSIZED TEE', cn:'米色宽松T恤', cat:'TOPS', season:'春夏',
   pal:['#d6cbb8','#bdb2a0','#8f8574'], notes:'AI 重绘自日常照 · 宽松落肩 · 百搭基础款'},
  {id:'s03', img:'images/s03_denim-jacket.webp', en:'BLUE DENIM TRUCKER JACKET', cn:'蓝色牛仔外套', cat:'JACKETS', season:'春秋',
   pal:['#4a6a8f','#7d99b5','#2e4258'], notes:'AI 重绘自日常照 · 经典四袋翻领 · 微水洗'},
  {id:'s04', img:'images/s04_cream-turtleneck.webp', en:'CREAM TURTLENECK SWEATER', cn:'米白高领毛衣', cat:'TOPS', season:'秋冬',
   pal:['#ece5d8','#d8cfc0','#b8ae9c'], notes:'AI 重绘自日常照 · 细腻针织 · 冬日打底'},
  {id:'s05', img:'images/s05_black-drawstring-pants.webp', en:'BLACK DRAWSTRING BARREL PANTS', cn:'黑色抽绳锥形裤', cat:'BOTTOMS', season:'四季',
   pal:['#1d1d1f','#4a4a4c','#d9d2c2'], notes:'AI 重绘自日常照 · 米色长抽绳 · 慵懒轮廓'},
  {id:'s06', img:'images/s06_camel-cord-pants.webp', en:'CAMEL SUEDE STRAIGHT PANTS', cn:'驼色麂皮感直筒裤', cat:'BOTTOMS', season:'春秋',
   pal:['#b3854f','#c79b64','#8a6238'], notes:'AI 重绘自日常照 · 复古色调 · 配棒球帽很衬'},
  {id:'s07', img:'images/s07_crop-denim-jacket.webp', en:'CROPPED RAW-HEM DENIM JACKET', cn:'浅色短款毛边牛仔外套', cat:'JACKETS', season:'春秋',
   pal:['#9db6cd','#c3d2df','#6f8ba3'], notes:'AI 重绘自日常照 · 毛边下摆 · 短款显比例'},
  {id:'s08', img:'images/s08_white-tank.webp', en:'WHITE FITTED TANK', cn:'白色修身背心', cat:'TOPS', season:'春夏',
   pal:['#eceff0','#d8dbdc','#1f1f1f'], notes:'AI 重绘自日常照 · 弹力修身 · 内搭神器'},
  {id:'s09', img:'images/s09_beige-blazer.webp', en:'OAT OVERSIZED BLAZER', cn:'燕麦色宽松西装外套', cat:'JACKETS', season:'春秋',
   pal:['#d9cfc0','#c5b9a6','#a2947e'], notes:'AI 重绘自日常照 · 廓形挺括 · 通勤休闲两用'},
  {id:'s10', img:'images/s10_denim-tie-top.webp', en:'DENIM TIE-FRONT TOP', cn:'牛仔无袖系结上衣', cat:'TOPS', season:'夏',
   pal:['#a8c0d4','#c9d8e4','#7c96ac'], notes:'AI 重绘自日常照 · 下摆系结 · 露腰元气'},
  {id:'s11', img:'images/s11_black-flare-pants.webp', en:'BLACK FLARE PANTS', cn:'黑色微喇裤', cat:'BOTTOMS', season:'四季',
   pal:['#141416','#3c3c3f','#77777a'], notes:'AI 重绘自日常照 · 高腰弹力 · 显腿长'},
  {id:'s12', img:'images/s12_white-dress.webp', en:'WHITE CRINKLE MIDI DRESS', cn:'白色褶皱肌理连衣裙', cat:'DRESSES', season:'夏',
   pal:['#f0efe9','#dcdad0','#2b2b2b'], notes:'AI 重绘自日常照 · 编织胸饰 · 大摆过膝'},
  {id:'s13', img:'images/s13_stripe-tee.webp', en:'STRIPED SLIM TEE', cn:'黑白条纹T恤', cat:'TOPS', season:'春夏',
   pal:['#2a2a28','#e8e3d8','#8b877c'], notes:'AI 重绘自日常照 · 细条纹 · 法式基础款'},
  {id:'s14', img:'images/s14_baggy-jeans.webp', en:'LIGHT-WASH BAGGY JEANS', cn:'浅蓝阔腿牛仔裤', cat:'BOTTOMS', season:'四季',
   pal:['#a7c0d8','#c6d6e5','#7e97ad'], notes:'AI 重绘自日常照 · 宽松直筒 · 配帆布鞋'},
  {id:'s15', img:'images/s15_pink-tee.webp', en:'PINK OVERSIZED TEE', cn:'粉色宽松T恤', cat:'TOPS', season:'夏',
   pal:['#f2c9cf','#e8b3bb','#d495a0'], notes:'AI 重绘自日常照 · 胸前小刺绣 · 温柔显白'},
  {id:'s16', img:'images/s16_white-shorts.webp', en:'WHITE PLEATED SHORTS', cn:'白色褶裥五分短裤', cat:'BOTTOMS', season:'夏',
   pal:['#f0efeb','#dcdad2','#c2c0b6'], notes:'AI 重绘自日常照 · 及膝伯慕达 · 清爽利落'},
  {id:'s17', img:'images/s17_mohair-sweater.webp', en:'BLUE-GRAY MOHAIR SWEATER', cn:'蓝灰条纹马海毛毛衣', cat:'TOPS', season:'秋冬',
   pal:['#93a2b8','#c3cbd8','#3e4a63'], notes:'AI 重绘自日常照 · 抽象笔触条纹 · 毛茸茸'},
];
const CATS = [
  {key:'ALL', cn:''}, {key:'TOPS', cn:''}, {key:'JACKETS', cn:''},
  {key:'BOTTOMS', cn:''}, {key:'DRESSES', cn:''}, {key:'OUTFITS', cn:''}
];
